name: Cinderela Clean Up
# Cleans up this repo every day at midnight

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  revert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Revert to specific commit
      run: |
        git reset --hard db428b23a10c65d675833bb3a7923e180fcfe612
        git push --force
