name: Cinderela Clean Up

on:
  workflow_dispatch:

jobs:
  revert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Revert to specific commit
      run: |
        git reset --hard v1.1
        git push --force
