name: Update Commit Hash
## IDEA: Make it run only when a PR is merged to main. But it has to be a PR

on:
#   pull_request:
#     branches:
#         - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to update'
        required: true
        default: 'main'

jobs:
  update-hash:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get latest commit hash
      id: get_commit
      run: echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: Update clean-up.yml with latest commit hash
      run: |
        COMMIT_HASH=${{ steps.get_commit.outputs.commit_hash }}
        cd .github/workflows
        sed -i "s/commit_hash:.*/commit_hash: $COMMIT_HASH/" clean-up.yml

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add -A
        git commit -m "Update commit hash to ${{ steps.get_commit.outputs.commit_hash }}"
        git push
